### ISSUE TITLE
Change icon size

### ISSUE THREAD

**Issue by robmr88** [clean-code-dev/animated_splash_screen#1]
Hi, is it possible to change the splash image size?

**Comment by Bestfastfire** [comment]
> Hi, is it possible to change the splash image size?

It will be deployed in the next version, thanks for the feedback.

**Comment by kkleber1991** [comment]
when I add the following line:
splash: Image.asset('img/img.jpg', width: 180, height: 180,)


does not resize my image size. When will this be possible?

It was vacilation of you not to make this attribute possible. But your package is great

**Comment by anthonycmeow** [comment]
@Bestfastfire We like this plugin so much except for this issue, is there any plan to fix this issue? Thanks so much.

**Comment by Bestfastfire** [comment]
Feature added.

**Comment by anthonycmeow** [comment]
@Bestfastfire  Thanks so much!

**Comment by Bestfastfire** [comment]
@anthonycmeow Sorry for the delay, last month I was stuck with work.

**Comment by anthonycmeow** [comment]
@Bestfastfire  No worries, I like this plugin, thanks again.
