### ISSUE TITLE
a way to do some background processing during the splash screen 

### ISSUE THREAD

**Issue by jdeltoft** [clean-code-dev/animated_splash_screen#11]
Is there a good example of calling some async function in the background during the spash?

**Comment by Bestfastfire** [comment]
You can do like this:

```
AnimatedSplashScreen.withScreenFunction(
  splash: 'images/splash.png',
  screenFunction: () async{
    await myFun();

    return MainScreen();
  }
)
```

**Comment by jdeltoft** [comment]
I ended up following this how to which was really nice. 

https://www.flutterclutter.dev/flutter/tutorials/beautiful-animated-splash-screen/2020/1108/
