### ISSUE TITLE
duration of animation

### ISSUE THREAD

**Issue by geekhenno** [clean-code-dev/animated_splash_screen#2]
How can i set the duration of the animation?

**Comment by Bestfastfire** [comment]
Has a field `duration`, you pass a value in milliseconds, if that value is less than 2500 (2.5 secs), it will automatically return to 2500.

**Comment by geekhenno** [comment]
The duration belongs just to the page,
But there is no duration to icon

**Comment by Bestfastfire** [comment]
> The duration belongs just to the page,
> But there is no duration to icon

Sorry about that, this function will be implemented in the next update, or if you want you can make a pull request now.
