### ISSUE TITLE
waiting for update

### ISSUE THREAD

**Issue by zakblacki** [clean-code-dev/animated_splash_screen#20]
> Because app depends on animated_splash_screen 1.1.0 which depends on page_transition 2.0.1-nullsafety.0, page_transition 2.0.1-nullsafety.0 is required.
> So, because app depends on page_transition ^1.1.7, version solving failed.
> pub get failed (1; So, because fayda depends on page_transition ^1.1.7, version solving failed.)

**Comment by Bestfastfire** [comment]
Use a old version `1.0.1+2`, sorry for the delay in resolving the issues, lately I've been very busy :/

**Comment by Bestfastfire** [comment]
Or you can too use `dependency_overrides` to override any dependencies that are causing conflict
