### ISSUE TITLE
PageTransitionType Error

### ISSUE THREAD

**Issue by ericksoto451** [clean-code-dev/animated_splash_screen#21]
![WhatsApp Image 2021-05-10 at 10 53 10 PM](https://user-images.githubusercontent.com/65363463/117755828-98402d00-b1e2-11eb-94ad-9e1c08c27e65.jpeg)
PageTransitionType is not being recognized

**Comment by ericksoto451** [comment]
Is there also a way to add a gradient color background?

**Comment by AntonyLeons** [comment]
just add this import:
```import 'package:page_transition/page_transition.dart';```
