### ISSUE TITLE
animated_splash_screen 1.1.0 depends on page_transition 2.0.1-nullsafety.0

### ISSUE THREAD

**Issue by zakblacki** [clean-code-dev/animated_splash_screen#32]
Fix this please 

> Because animated_splash_screen 1.1.0 depends on page_transition 2.0.1-nullsafety.0 and no versions of animated_splash_screen match >1.1.0 <2.0.0, animated_splash_screen ^1.1.0 requires page_transition 2.0.1-nullsafety.0.
So, because fayda depends on both animated_splash_screen ^1.1.0 and page_transition ^2.0.4, version solving failed.
pub get failed (1; So, because fayda depends on both animated_splash_screen ^1.1.0 and page_transition ^2.0.4, version solving failed.)

**Comment by zakblacki** [comment]
workaround 
`  animated_splash_screen:
    git:
      url: https://github.com/clean-code-dev/animated_splash_screen.git
      ref: master`

**Comment by Ulukbek-01** [comment]
I am facing the same issue. Have anyone fixed this issue?

**Comment by Bestfastfire** [comment]
Solved
