### ISSUE TITLE
All route was down after import this package

### ISSUE THREAD

**Issue by goldenmoon67** [clean-code-dev/animated_splash_screen#37]
Exception has occurred.
FlutterError (Could not find a generator for route RouteSettings("/MyTeamsScreen", null) in the _WidgetsAppState.
Make sure your root app widget has provided a way to generate
this route.
Generators for routes are searched for in the following order:
 1. For the "/" route, the "home" property, if non-null, is used.
 2. Otherwise, the "routes" table is used, if it has an entry for the route.
 3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not handled by "home" and "routes".
 4. Finally if all else fails onUnknownRoute is called.
Unfortunately, onUnknownRoute was not set.)

**Comment by goldenmoon67** [comment]
my fault :)

**Comment by spandan3001** [comment]
> Exception has occurred. FlutterError (Could not find a generator for route RouteSettings("/MyTeamsScreen", null) in the _WidgetsAppState. Make sure your root app widget has provided a way to generate this route. Generators for routes are searched for in the following order:
> 
> 1. For the "/" route, the "home" property, if non-null, is used.
> 2. Otherwise, the "routes" table is used, if it has an entry for the route.
> 3. Otherwise, onGenerateRoute is called. It should return a non-null value for any valid route not handled by "home" and "routes".
> 4. Finally if all else fails onUnknownRoute is called.
>    Unfortunately, onUnknownRoute was not set.)

K

**Comment by spandan3001** [comment]
DID YOU GET THE ANSWER

**Comment by goldenmoon67** [comment]
actually It was really easy problem but I could not remember it. be sure you do everything true. It is not a problem. it is developer mistake. I remember like that.

**Comment by goldenmoon67** [comment]
one more note. ıf you implemented any router package. use it to use splash screen as a first screen
