### ISSUE TITLE
When using type "scale" you need argument: 'alignment'

### ISSUE THREAD

**Issue by moluopro** [clean-code-dev/animated_splash_screen#42]
try official demo and get :

When using type "scale" you need argument: 'alignment'  
'package:page_transition/src/page_transition.dart':  
Failed assertion: line 174 pos 16: 'alignment != null'   
<img width="649" alt="屏幕截图 2022-08-10 105428" src="https://user-images.githubusercontent.com/55039286/183800364-ee223291-abdb-469a-ae53-e512e2d6c98d.png">
<img width="801" alt="屏幕截图 2022-08-10 105524" src="https://user-images.githubusercontent.com/55039286/183800369-e8f3b3bc-40ad-462d-a920-014e29b89f10.png">

**Comment by V-outsider** [comment]
It has transitions which doesnt need alignment, but the doesnt work too, without error, just no effect

**Comment by Bestfastfire** [comment]
Pull request merged, pls use this package by git version:

```
dependencies:
...
    animated_splash_screen:
        git: 'https://github.com/clean-code-dev/animated_splash_screen'
...
```
