### ISSUE TITLE
White screen showing before splash screen

### ISSUE THREAD

**Issue by tinashepb** [clean-code-dev/animated_splash_screen#43]
Good day. 

Please could you kindly assist. I'm getting a blank white screen for a few seconds on Android before the actual splash screen loads. 

Regards.

**Comment by Bestfastfire** [comment]
This no problem with this lib, this is with flutter initial load, to fix this you need change native splashscreen for each platform (ios/android) please check this: https://stackoverflow.com/questions/56168832/flutter-app-on-start-it-is-showing-white-screen-for-few-second
