### ISSUE TITLE
PageTransitionType don't found

### ISSUE THREAD

**Issue by FabioTambu** [clean-code-dev/animated_splash_screen#50]
Hi, I'm using your package and I'm having a problem with the PageTransitionType.
When I try to add it it says it doesn't exist and reports it as an error, here is my code:

```
return AnimatedSplashScreen(
          duration: 5000,
          splash: const Image(image: AssetImage('assets/images/logo_tefatech.png'), width: 200, height: 200),
          splashTransition: SplashTransition.fadeTransition,
          backgroundColor: Colors.blue,
          pageTransitionType: PageTransitionType.scale,
          nextScreen: const CheckUserLogin()
      );
```

**Comment by WelintonJuniorCeconello** [comment]
Olá @FabioTambu !
Adicione:  import 'package:page_transition/page_transition.dart'

**Comment by WelintonJuniorCeconello** [comment]
Hello, @FabioTambu!

Add: import 'package:page_transition/page_transition.dart';
