### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by muzamilhaq** [clean-code-dev/animated_splash_screen#6]
I have tried resizing with height width and scale code,but still not happen,

`home: AnimatedSplashScreen(
        splash: Image.asset("asset/logo.png",height: 400,width: 400),
        nextScreen: MyHomePage(title:"Home"),
        backgroundColor: Colors.cyanAccent,
      ),`

**Comment by maylortaylor** [comment]
I'm having the same issue.
How would I resize the image to be bigger?
