### ISSUE TITLE
PageTransitionType  throws an error

### ISSUE THREAD

**Issue by Sharif-Niloy** [clean-code-dev/animated_splash_screen#7]
This is a really useful package & I am using the version (1.0.1+2). But I am facing the problem described as below.

PageTransitionType.[TYPE]  does not work. It throws an error that says: " **Undefined name 'PageTranstionType'.
Try correcting the name to one that is defined, or defining the name. dart(undefined_identifier)** "

Please resolve this issue.
![error](https://user-images.githubusercontent.com/39795280/99091510-34092b80-25fa-11eb-9b4c-fb925dfa1bad.PNG)

**Comment by AntonyLeons** [comment]
yep had this too, just add this import
`import 'package:page_transition/page_transition.dart';`

**Comment by Sharif-Niloy** [comment]
Thank you so much @AntonyLeons ... This solved my issue completely !
