### ISSUE TITLE
Image size is not working

### ISSUE THREAD

**Issue by maylortaylor** [clean-code-dev/animated_splash_screen#8]
I can't seem to get my splash image to be any bigger.

```
splash: Image.asset("assets/images/splash.png",
                    height: 1200, width: 1200),
```

I'm using version `^1.0.1+2`

**Comment by maylortaylor** [comment]
I finally got it working correctly (i think)

```
splash: Container(
                height: double.infinity,
                width: double.infinity,
                child: FittedBox(child: Image.asset("assets/images/splash.png"),
                fit: BoxFit.cover))
```

**Comment by Bestfastfire** [comment]
> I finally got it working correctly (i think)
> 
> ```
> splash: Container(
>                 height: double.infinity,
>                 width: double.infinity,
>                 child: FittedBox(child: Image.asset("assets/images/splash.png"),
>                 fit: BoxFit.cover))
> ```

In fact, there is a field for this in the object itself:

```
AnimatedSplashScreen(
   splashIconSize: my_size,
   ...
)

```
I'm sorry for the delay in replying

**Comment by Rizatzmi** [comment]
> I finally got it working correctly (i think)
> 
> ```
> splash: Container(
>                 height: double.infinity,
>                 width: double.infinity,
>                 child: FittedBox(child: Image.asset("assets/images/splash.png"),
>                 fit: BoxFit.cover))
> ```

is that can make splash screen to full screen? @maylortaylor
